/**
 * Field — a labelled control with its description and error message.
 *
 * The ids that tie the three together are generated by `Field` and read from
 * context, so the caller never wires `htmlFor` or `aria-describedby` by hand:
 *
 *   <Field invalid={Boolean(error)}>
 *     <FieldLabel>Volume label</FieldLabel>
 *     <TextInput value={name} onInput={…} />
 *     <FieldDescription>Up to eleven characters.</FieldDescription>
 *   </Field>
 *
 * When `invalid` is set the control points at the error instead of the
 * description, so a screen reader reads the problem rather than the hint.
 */
import { $id, useContext } from "yract-beta";
import type { Children, PropsWithChildren } from "yract-beta";
import type { SyntheticEvent } from "yract-beta";
import { FieldContext } from "./contexts";

export interface FieldProps extends PropsWithChildren {
  invalid?: boolean;
}

export function* Field({ invalid = false, children }: FieldProps) {
  const controlId = yield* $id();
  const descriptionId = yield* $id();
  const errorId = yield* $id();

  return (
    <FieldContext value={{ controlId, descriptionId, errorId, invalid }}>
      <div className="dos-field">{children}</div>
    </FieldContext>
  );
}

export function* FieldLabel({ children }: PropsWithChildren) {
  const { controlId } = yield* useContext(FieldContext);
  return (
    <label className="dos-label" htmlFor={controlId}>
      {children}
    </label>
  );
}

export function* FieldDescription({ children }: PropsWithChildren) {
  const { descriptionId } = yield* useContext(FieldContext);
  return (
    <p className="dos-desc" id={descriptionId}>
      {children}
    </p>
  );
}

/** Error text. Renders nothing unless its `Field` is marked invalid. */
export function* FieldError({ children }: PropsWithChildren) {
  const { errorId, invalid } = yield* useContext(FieldContext);
  return (
    <p className="dos-error" id={errorId} shown={invalid}>
      {children}
    </p>
  );
}

function describedBy(invalid: boolean, descriptionId: string, errorId: string): string {
  return invalid ? errorId : descriptionId;
}

export interface TextInputProps {
  value: string;
  /** Receives the new value, not the DOM event — the control unwraps it. */
  onChange?: (value: string) => void;
  placeholder?: string;
  type?: "text" | "email" | "password" | "search" | "tel" | "url";
}

export function* TextInput({ value, onChange, placeholder, type = "text" }: TextInputProps) {
  const { controlId, descriptionId, errorId, invalid } = yield* useContext(FieldContext);
  return (
    <input
      className="dos-input"
      id={controlId}
      type={type}
      value={value}
      placeholder={placeholder}
      aria-invalid={invalid ? "true" : undefined}
      aria-describedby={describedBy(invalid, descriptionId, errorId)}
      onInput={(event: SyntheticEvent<Event, HTMLInputElement>) =>
        onChange?.(event.currentTarget?.value ?? "")
      }
    />
  );
}

export interface SelectProps extends PropsWithChildren {
  value: string;
  onChange?: (value: string) => void;
}

/** Native select behind a drawn arrow, so the platform picker still opens. */
export function* Select({ value, onChange, children }: SelectProps) {
  const { controlId, descriptionId, errorId, invalid } = yield* useContext(FieldContext);
  return (
    <div className="dos-select-wrap">
      <select
        className="dos-select"
        id={controlId}
        value={value}
        aria-describedby={describedBy(invalid, descriptionId, errorId)}
        onChange={(event: SyntheticEvent<Event, HTMLSelectElement>) =>
          onChange?.(event.currentTarget?.value ?? "")
        }
      >
        {children}
      </select>
    </div>
  );
}

export interface TextAreaProps {
  value: string;
  onChange?: (value: string) => void;
  placeholder?: string;
  rows?: number;
}

export function* TextArea({ value, onChange, placeholder, rows }: TextAreaProps) {
  const { controlId, descriptionId, errorId, invalid } = yield* useContext(FieldContext);
  return (
    <textarea
      className="dos-textarea"
      id={controlId}
      value={value}
      rows={rows}
      placeholder={placeholder}
      aria-describedby={describedBy(invalid, descriptionId, errorId)}
      onInput={(event: SyntheticEvent<Event, HTMLTextAreaElement>) =>
        onChange?.(event.currentTarget?.value ?? "")
      }
    />
  );
}

export interface RangeProps {
  value: number;
  min: number;
  max: number;
  step?: number;
  onChange?: (value: number) => void;
  /**
   * Spoken value. Without it a screen reader announces a bare number and the
   * listener never learns the unit.
   */
  valueText?: Children;
}

export function* Range({ value, min, max, step = 1, onChange, valueText }: RangeProps) {
  const { controlId, descriptionId, errorId, invalid } = yield* useContext(FieldContext);
  return (
    <input
      className="dos-range"
      id={controlId}
      type="range"
      value={String(value)}
      min={String(min)}
      max={String(max)}
      step={String(step)}
      aria-valuetext={valueText === undefined ? undefined : String(valueText)}
      aria-describedby={describedBy(invalid, descriptionId, errorId)}
      onInput={(event: SyntheticEvent<Event, HTMLInputElement>) =>
        onChange?.(Number(event.currentTarget?.value ?? min))
      }
    />
  );
}
